apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yml
- rolebinding.yml
- attrrole-binding.yml
- sa.yml
- clusterrole.yml
- scc.yml
- scc-binding.yml

namespace: openshift-logging
