apiVersion: v1
kind: Service
metadata:
  name: splunk-hec
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - appProtocol: https
      name: admin
      port: 8000
      protocol: TCP
      targetPort: 8000
    - appProtocol: https
      name: hec
      port: 8088
      protocol: TCP
      targetPort: 8088
    - appProtocol: grpc
      name: otlp-grpc
      port: 4317
      protocol: TCP
      targetPort: 4317
    - appProtocol: http
      name: otlp-http
      port: 4318
      protocol: TCP
      targetPort: 4318
  selector:
    app: splunk-hec
  sessionAffinity: None
  type: ClusterIP
